name: Frontend e2e
on:
  push:
  pull_request:

jobs:
  e2e-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies for frontend
        working-directory: frontend
        run: npm ci

      - name: Install Playwright
        working-directory: frontend
        run: npx playwright install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Start frontend in the background
        working-directory: frontend
        run: nohup npm start &

      - name: Run Playwright tests
        working-directory: frontend
        run: npm run test:e2e
