name: Frontend coverage
on:
  push:
  pull_request:

jobs:
  coverage-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies for frontend
        working-directory: frontend
        run: npm ci

      - name: Check for global coverage threshold message
        working-directory: frontend
        run: |
          COVERAGE_OUTPUT=$(npm run test:coverage 2>&1)
          echo "$COVERAGE_OUTPUT"
          if echo "$COVERAGE_OUTPUT" | grep -qE 'coverage threshold for'; then
            echo "Error: Global coverage threshold not met";
            exit 1;
          else
            echo "Global coverage threshold met, proceeding...";
          fi