name: Frontend test
on:
  push:
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Check for .only in tests
        run: |
          if grep -r "\.only" ./src/tests; then
            echo "Error: Found .only in test files!"
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies for frontend
        working-directory: frontend
        run: npm ci
      
      - name: Run Jest tests with coverage (Frontend)
        working-directory: frontend
        run: npm test
